### ISSUE TITLE
Template is empty and not useful

### ISSUE THREAD

**Issue by radeva** [amirhosseinab/tns-template-blank-vue#1]
Hi @amirhosseinab ,

We're trying to publish a fully functional NativeScript Vue Blank template to NPM, but noticed that you have published the one having the same name almost an year ago. From the package, the repo and the downloads from NPM it is visible that the package is empty and not used.

Would you mind unpublishing the npm package so that NativeScript Vue community can get advantage of the fully functional one we're planning to publish?

Thanks in advance for your cooperation!

Veselina Radeva,
NativeScript Core Team

**Comment by amirhosseinab** [comment]
Hi @radeva ,

First of all I apologized for my delayed response.
I'v tried to unpublish this package, but noticed that npm only allows to unpublish packages after 72 hours of publishing them.
I'v already deprecated the package and I contacted npm support team, asked them to remove this package.

> Hello,
> 
> I'v published tns-template-blank-vue package about a year ago, recently I got a message form NativeScript Core Team by this issue. I'v tried to unpublish this package but I can't.
> Would you please help me to remove/unpublish this package?
> 
> Best Regards
> Amir Hossein Abdolkhalegh

So, it will be available for community after this process

Amir Hossein Abdolkhalegh

**Comment by radeva** [comment]
Thanks a lot @amirhosseinab !

Indeed, to unpublish after 72h you need to explicitly contact the support. We'll follow the availability in npm.

Let us know if you have any feedback for NativeScript, we'll be happy to hear from you :)

**Comment by amirhosseinab** [comment]
Thank you @radeva,

npm support respond me, and they will proceed the unpublishing of package.

**Comment by amirhosseinab** [comment]
Hi @radeva,

I noticed that the package unpublished by npm support team, I want to inform you about that.

**Comment by radeva** [comment]
Thanks @amirhosseinab ,

We already published the new one. Thanks for your cooperation!
